const assert=require('node:assert/strict');
const C=require('../src/core.js');let checks=0;
function test(name,fn){fn();checks++;console.log('PASS',name);}
const tiers=[{limit:1000,price:.2},{limit:10000,price:.15},{limit:50000,price:.1},{limit:null,price:.07}];
test('CPF válido e pontuação',()=>assert.equal(C.validateDocument('529.982.247-25').valid,true));
test('CPF repetido rejeitado',()=>assert.equal(C.validateDocument('11111111111').valid,false));
test('CPF dígito incorreto',()=>assert.equal(C.validateDocument('52998224724').valid,false));
test('CNPJ numérico válido',()=>assert.equal(C.validateDocument('11.222.333/0001-81').valid,true));
test('CNPJ alfanumérico válido',()=>assert.equal(C.validateDocument('12.ABC.345/01DE-35').valid,true));
test('Letras de CNPJ preservadas',()=>assert.equal(C.cleanDocument('12.ABC.345/01DE-35'),'12ABC34501DE35'));
test('CNPJ com DV inválido',()=>assert.equal(C.validateDocument('12ABC34501DE34').valid,false));
test('Caractere indevido não removido',()=>assert.equal(C.validateDocument('529$98224725').valid,false));
test('Valor ausente',()=>assert.equal(C.validateDocument('').reason,'Documento ausente'));
test('Não pressupõe zeros perdidos',()=>assert.equal(C.validateDocument('1234567890').valid,false));
test('Zero registros, zero valor',()=>assert.equal(C.progressivePrice(0,tiers).totalCents,0));
test('Faixa exata 1000',()=>assert.equal(C.progressivePrice(1000,tiers).totalCents,20000));
test('Faixa seguinte apenas parcela adicional',()=>assert.equal(C.progressivePrice(1001,tiers).totalCents,20015));
test('12000 calculados por parcelas',()=>assert.equal(C.progressivePrice(12000,tiers).totalCents,175000));
test('Última faixa sem limite',()=>assert.equal(C.progressivePrice(50001,tiers).totalCents,555007));
test('Quantidade negativa rejeitada',()=>assert.throws(()=>C.progressivePrice(-1,tiers)));
test('Faixas invertidas rejeitadas',()=>assert.throws(()=>C.progressivePrice(10,[{limit:100,price:1},{limit:50,price:1},{limit:null,price:1}])));
test('Faixa final finita rejeitada',()=>assert.throws(()=>C.progressivePrice(10,[{limit:100,price:1}])));
test('CSV com separador e aspas',()=>assert.deepEqual(C.parseCSV('a;b\n"um;dois";"x""y"\n'),[['a','b'],['um;dois','x"y']]));
test('CSV com nova linha em campo',()=>assert.deepEqual(C.parseCSV('a,b\n"x\ny",z'),[['a','b'],['x\ny','z']]));
test('CSV com aspas inválidas é rejeitado',()=>assert.throws(()=>C.parseCSV('a,b\n"x,y')));
test('Exportação mitiga fórmulas',()=>assert.ok(C.toCSV([['=1+1']]).includes("'=1+1")));
test('Categorias de elegibilidade sem sobreposição',()=>{const a=C.analyzeRows(C.createSample(),1);assert.deepEqual([a.total,a.eligible,a.cpf,a.cnpj,a.duplicated,a.invalid,a.missing],[12000,10800,8100,2700,800,300,100]);assert.equal(a.total,a.eligible+a.duplicated+a.invalid+a.missing);});
test('Linhas vazias separadas da base',()=>{const a=C.analyzeRows([['doc'],[],['52998224725'],['529.982.247-25'],['11111111111']],0);assert.deepEqual([a.total,a.blank,a.eligible,a.duplicated,a.invalid],[3,1,1,1,1]);});
test('Descadastramento bloqueia novas abordagens',()=>assert.equal(C.classifyReply('Não quero receber novos e-mails.').blocked,true));
test('Solicitação de orçamento',()=>assert.equal(C.classifyReply('Gostaria de uma proposta.').label,'Solicita proposta'));
test('Mensagem inconclusiva exige revisão',()=>assert.equal(C.classifyReply('Talvez.').label,'Revisão humana'));
test('Sexta + 1 dia útil é segunda',()=>assert.equal(C.businessDays('2026-10-09T12:00:00',1).slice(0,10),'2026-10-12'));
test('Feriados explicitamente configurados são respeitados',()=>assert.equal(C.businessDays('2026-10-09T12:00:00',1,['2026-10-12']).slice(0,10),'2026-10-13'));
test('Técnico indisponível não recebe atribuição',()=>assert.equal(C.assignTechnician(10,[{name:'A',capacity:100,available:false},{name:'B',capacity:100,available:true}],[]).name,'B'));
test('Menor carga proporcional',()=>assert.equal(C.assignTechnician(10,[{name:'A',capacity:100,available:true},{name:'B',capacity:200,available:true}],[{tech:'A',qty:50,status:'Em processamento'},{tech:'B',qty:50,status:'Em processamento'}]).name,'B'));
test('Pedidos entregues não contam na fila',()=>assert.equal(C.assignTechnician(10,[{name:'A',capacity:100,available:true}],[{tech:'A',qty:500,status:'Entregue'}]).load,0));
test('Sem equipe disponível retorna nulo',()=>assert.equal(C.assignTechnician(10,[],[]),null));
console.log('TOTAL:',checks,'tests passed');
